spring:
  application:
    name: homewizard-api

output:
  most-detailed:
    enabled: true
    fetch-rate-in-milliseconds: 10000
    output-file-name: smartMeterOutput10seconds.csv

  hour:
    enabled: true
    output-file-name: smartMeterOutputHour.csv

  day:
    enabled: true
    output-file-name: smartMeterOutputDay.csv
