spring:
  datasource:
    url: jdbc:postgresql://192.168.2.39:5432/home-monitor
    driver-class-name: org.postgresql.Driver
    username: define_in_override
    password: define_in_override

homewizard:
  enabled: true
  username: define_in_override
  password: define_in_override

tado:
  enabled: true
  username: define_in_override
  password: define_in_override

eneco:
  enabled: true
  username: define_in_override
  password: define_in_override

raspberrypi:
  enabled: true

dbstats:
  enabled: true
  dropbox_uploader: /home/martinschijf/dropbox-uploader/dropbox_uploader.sh