spring:
  application:
    name: homewizard-api

output:
  variable-time-file-name: smartMeterOutput.csv
  hour-file-name: smartMeterOutputHour.csv
  day-file-name: smartMeterOutputDay.csv
  path: ./data

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info,metric
