spring:
  application:
    name: homewizard-api

output:
  base-file-name: smartMeterOutput
  path: ./data

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info,metric
