spring:
  application:
    name: home-monitoring
  main:
    banner-mode: "off"
  jpa:
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5432/home-monitor
    username: home-monitor
    password: home-monitor
    driver-class-name: org.postgresql.Driver

homewizard:
    enabled: false
    energyBaseRestUrl: http://192.168.2.40/api/v1
    waterBaseRestUrl: http://192.168.2.42/api/v1
    initialWaterValue: 799.017

tado:
  enabled: false
  tokenUrl: https://auth.tado.com/oauth/token
  clientId: public-api-preview
  clientSecret: 4HJGRffVR8xb3XdEUQpjgZ1VplJi6Xgw
  username: via application.yml on remote location
  password: via application.yml on remote location
  baseRestUrl: https://my.tado.com/api/v2

raspberrypi:
  enabled: false

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info,metric
