spring:
  application:
    name: home-monitoring

homewizard:
    url: http://192.168.2.40

output:
  base-file-name: smartMeterOutput
  path: ./data

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info,metric
