spring:
  application:
    name: home-monitoring

homewizard:
    url: http://192.168.2.40

tado:
  envUrl: https://app.tado.com/env.js
  clientId: tado-web-app
  tokenUrl: https://auth.tado.com/oauth/token
  username: via-commandline-arguments --tado.username=<username>
  password: via-commandline-arguments --tado.password=<password>
  secret: wZaRN7rpjn3FoNyF5IFuxg9uMzYJcvOoQ8QWiIqS3hfk6gLhVlG57j5YNoZL2Rtc
  baseRestUrl: https://my.tado.com/

output:
  base-file-name: smartMeterOutput
  path: ./data

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info,metric
