spring:
  application:
    name: home-monitoring
  main:
    banner-mode: off
  jpa:
    open-in-view: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/home-monitor
    username: home-monitor
    password: home-monitor
  flyway:
    user: home-monitor
    password: home-monitor
    enabled: true
    baselineOnMigrate: true
    baseline-version: 0

springdoc:
  swagger-ui:
    tagsSorter: alpha

home-monitor:
  mock-location: ./mock

  homewizard:
    electricityBaseRestUrl: http://192.168.2.40/api/v1
    waterBaseRestUrl: http://192.168.2.42/api/v1
    initialWaterValue: 799.017

  eneco:
    initialDate: 2024-01-01T00:00:00
    initialHeathValue: 196.196
    username: not_for_dev
    password: not_for_dev

  tado:
    deviceUrl: https://login.tado.com/oauth2/device_authorize
    tokenUrl: https://login.tado.com/oauth2/token
    clientId: 1bb50063-6b0c-4d11-bd99-387f4a91cc46
    baseRestUrl: https://my.tado.com/api/v2

  system:
    cpuTemperatureCmd: cat ${home-monitor.mock-location}/sys_class_thermal_thermal_zone0_temp
    gpuTemperatureCmd: ${home-monitor.mock-location}/vcgencmd.sh measure_temp
    dropbox:
        dropbox_uploader: ${home-monitor.mock-location}/dropbox_uploader.sh
        root: Backup/home-monitor/
    backup:
      script: ${home-monitor.mock-location}/backup.sh
      keep: 3

  log:
    location: ${home-monitor.mock-location}/log

  scheduler:
    electricity:
      detailed: "-"
      regular: "-"
      cleanup: "-"
    water:
      detailed: "-"
      regular: "-"
      cleanup: "-"
    tado:
      regular: "-"
      hourSummary: "-"
      deviceState: "-"
      cleanup: "-"
    heath:
      updateEnecoStats: "-"
    system:
      temperature: "-"
      dbStats: "-"
      backup: "-"
      dropboxFreeSpace: "-"


management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info,metric,env
#  endpoint:
#    env:
#      show-values: ALWAYS










