spring:
  application:
    name: home-monitoring
  main:
    banner-mode: "off"
  jpa:
    open-in-view: false
  datasource:
    url: jdbc:mariadb://localhost:3306/home-monitor
    username: home-monitor
    password: home-monitor
    driver-class-name: org.mariadb.jdbc.Driver

homewizard:
    enabled: false
    energyBaseRestUrl: http://192.168.2.40/api/v1
    waterBaseRestUrl: http://192.168.2.42/api/v1
    initialWaterValue: 799.017

tado:
  enabled: false
  tokenUrl: https://auth.tado.com/oauth/token
  clientId: public-api-preview
  clientSecret: 4HJGRffVR8xb3XdEUQpjgZ1VplJi6Xgw
  username: via application.yml on remote location
  password: via application.yml on remote location
  baseRestUrl: https://my.tado.com/api/v2

raspberrypi:
  enabled: false

weerlive:
  enabled: false
  baseRestUrl: https://weerlive.nl/api/weerlive_api_v2.php
  apiKey: via application.yml on remote location
  locationCoordinateN: 52.0248
  locationCoordinateE: 5.0918

eneco:
  enabled: false

data-output:
  path: ./data

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info,metric
