spring:
  config:
    import: "optional:/home/martinschijf/application/config/secrets.yml"
  datasource:
    url: jdbc:postgresql://192.168.2.39:5432/home-monitor
    username: ${home-monitor.datasource.username}
    password: ${home-monitor.datasource.password}
  flyway:
    user: ${home-monitor.datasource.username}
    password: ${home-monitor.datasource.password}

home-monitor:
#  homewizard:
#    username: defined_in_secrets
#    password: defined_in_secrets

#  tado:
#    username: defined_in_secrets
#    password: defined_in_secrets

#  eneco:
#    username: defined_in_secrets
#    password: defined_in_secrets

  system:
    cpuTemperatureCmd: cat /sys/class/thermal/thermal_zone0/temp
    gpuTemperatureCmd: vcgencmd measure_temp
    dropbox:
      dropbox_uploader: /home/martinschijf/dropbox-uploader/dropbox_uploader.sh
      root: Backup/home-monitor/
    backup:
      script: /home/martinschijf/home-monitor-backup-script/backup.sh
      keep: 672

  scheduler:
    electricity:
      detailed: 0/10 * * * * *
      regular: 0 * * * * *
    water:
      detailed: 0/10 * * * * *
      regular: 0 * * * * *
    tado:
      regular: 0 * * * * *
      hourSummary: 0 0 * * * *
    heath:
      updateEnecoStats: 0 0 1-23/2 * * *
    system:
      temperature: 0 * * * * *
      dbStats: 0 * * * * *
      backup: 0 15 1-23/2 * * *
      dropboxFreeSpace: 0 20 1-23/2 * * *


  log:
    location: /home/martinschijf/application/home-monitor/log