spring:
  application:
    name: home-monitoring

homewizard:
    enabled: true
    baseRestUrl: http://192.168.2.40/api/v1

tado:
  enabled: true
  tokenUrl: https://auth.tado.com/oauth/token
  clientId: public-api-preview
  clientSecret: 4HJGRffVR8xb3XdEUQpjgZ1VplJi6Xgw
  username: via application.yml on remote location
  password: via application.yml on remote location
  baseRestUrl: https://my.tado.com/api/v2

raspberrypi:
  enabled: true

output:
  path: ./data

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info,metric
