spring:
  config:
    import: "optional:/home/martinschijf/application/config/secrets.yml"
  datasource:
    url: jdbc:postgresql://192.168.2.39:5432/home-monitor
    username: ${home-monitor.datasource.username}
    password: ${home-monitor.datasource.password}
  flyway:
    user: ${home-monitor.datasource.username}
    password: ${home-monitor.datasource.password}

home-monitor:
  homewizard:
    enabled: true
#    username: defined_in_secrets
#    password: defined_in_secrets

  tado:
    enabled: true
#    username: defined_in_secrets
#    password: defined_in_secrets

  eneco:
    enabled: true
#    username: defined_in_secrets
#    password: defined_in_secrets

  raspberrypi:
    enabled: true

  dbstats:
    enabled: true
    dropbox_uploader: /home/martinschijf/dropbox-uploader/dropbox_uploader.sh

  log:
    location: /home/martinschijf/application/home-monitor/log