{
 "title": "Home-monitor",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "15s",
 "panels": [
  { "title": "System - Database - Process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Disk size Free",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "disk_free_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "DB size",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "homeMonitorDbSize", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Dropbox space",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "rawSql": "SELECT free_space FROM backup_stats WHERE id=1"
    }
   ]
  },
  {
   "title": "Low Battery Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(1) FROM tado_device_state WHERE battery_state != 'NORMAL' "
    }
   ]
  },
  {
   "title": "Last Backup",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT extract(epoch from (now() - last)) FROM backup_stats WHERE id=1"
    }
   ]
  },
  {
   "title": "Error",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "sum(logback_events_total{level=\"error\"}) ",
     "legendFormat": "Error"
    }
   ]
  },
  {
   "title": "Warning",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "sum(logback_events_total{level=\"warn\"})",
     "legendFormat": "Warning"
    }
   ]
  },
  {
   "title": "Last restart",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time FROM admin_timestamp WHERE key='LAST_STARTUP_TIME'"
    }
   ]
  },
  {
   "title": "CPU Usage/Temperature",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "system_cpu_usage{}", "legendFormat": "Usage" },
    { "expr": "systemCpuTemperature", "legendFormat": "Temperature" }
   ]
  },
  {
   "title": "Eneco Imports Succes",
   "type": "barchart",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 5 },
   "targets": [
    {
     "rawSql": "select time, success::Integer, (not success)::Integer as failed from eneco_stats where $__timeFilter(time) order by time"
    }
   ]
  },
  {
   "title": "Binnen en buiten klimaat (stand)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }
  },
  {
   "title": "Temperatuur",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT distinct\n    inside_temperature as Woonkamer\nFROM tado\nwhere $__timeFilter(\"time\") and zone_id = 1\n;"
    },
    {
     "rawSql": "SELECT distinct\n    inside_temperature as Slaapkamer\nFROM tado\nwhere $__timeFilter(\"time\") and zone_id = 3\n;"
    },
    {
     "rawSql": "SELECT distinct\n    inside_temperature as Werkkamer\nFROM tado\nwhere $__timeFilter(\"time\") and zone_id = 6\n;"
    },
    {
     "rawSql": "SELECT distinct\n    inside_temperature as Badkamer\nFROM tado\nwhere $__timeFilter(\"time\") and zone_id = 7\n;"
    }
   ]
  },
  {
   "title": "heating power%",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 9, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT distinct\n    heating_power_percentage as Woonkamer\nFROM tado\nwhere $__timeFilter(\"time\") and zone_id = 1\n;"
    },
    {
     "rawSql": "SELECT distinct\n    heating_power_percentage as Slaapkamer\nFROM tado\nwhere $__timeFilter(\"time\") and zone_id = 3\n;"
    },
    {
     "rawSql": "SELECT distinct\n    heating_power_percentage as Werkkamer\nFROM tado\nwhere $__timeFilter(\"time\") and zone_id = 6\n;"
    },
    {
     "rawSql": "SELECT distinct\n    heating_power_percentage as Badkamer\nFROM tado\nwhere $__timeFilter(\"time\") and zone_id = 7\n;"
    }
   ]
  },
  {
   "title": "Buiten",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    outside_temperature as Temperatuur,\n    humidity_percentage as \"vocht%\"\nFROM weather\nwhere $__timeFilter(\"time\") order by time desc limit 1\n;"
    },
    {
     "rawSql": "SELECT solar_intensity_percentage as \"zon intensiteit%\"\nFROM tado_outside WHERE $__timeFilter(\"time\") ORDER BY \"time\" DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Buiten",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\nCASE \n        WHEN wind_kph < 1   THEN 0\n        WHEN wind_kph < 6   THEN 1\n        WHEN wind_kph < 12  THEN 2\n        WHEN wind_kph < 20  THEN 3\n        WHEN wind_kph < 29  THEN 4\n        WHEN wind_kph < 39  THEN 5\n        WHEN wind_kph < 50  THEN 6\n        WHEN wind_kph < 62  THEN 7\n        WHEN wind_kph < 75  THEN 8\n        WHEN wind_kph < 89  THEN 9\n        WHEN wind_kph < 103 THEN 10\n        WHEN wind_kph < 118 THEN 11\n        ELSE 12\n        END AS wind,\n        wind_dir as richting\nFROM weather\nwhere $__timeFilter(\"time\") order by time desc limit 1\n;"
    },
    {
     "rawSql": "SELECT (uv/7.8)*(100-cloud) as \"zon% calc\" FROM weather WHERE $__timeFilter(\"time\") ORDER BY \"time\" DESC limit 1"
    }
   ]
  },
  {
   "title": "Vocht%",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT distinct\n    humidity_percentage as Woonkamer\nFROM tado\nwhere $__timeFilter(\"time\") and zone_id = 1\n;"
    },
    {
     "rawSql": "SELECT distinct\n    humidity_percentage as Slaapkamer\nFROM tado\nwhere $__timeFilter(\"time\") and zone_id = 3\n;"
    },
    {
     "rawSql": "SELECT distinct\n    humidity_percentage as Werkkamer\nFROM tado\nwhere $__timeFilter(\"time\") and zone_id = 6\n;"
    },
    {
     "rawSql": "SELECT distinct\n    humidity_percentage as Badkamer\nFROM tado\nwhere $__timeFilter(\"time\") and zone_id = 7\n;"
    }
   ]
  },
  {
   "title": "Setting Temperatuur",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 9, "x": 9, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT distinct\n    setting_temperature as Woonkamer\nFROM tado\nwhere $__timeFilter(\"time\") and zone_id = 1\n;"
    },
    {
     "rawSql": "SELECT distinct\n    setting_temperature as Slaapkamer\nFROM tado\nwhere $__timeFilter(\"time\") and zone_id = 3\n;"
    },
    {
     "rawSql": "SELECT distinct\n    setting_temperature as Werkkamer\nFROM tado\nwhere $__timeFilter(\"time\") and zone_id = 6\n;"
    },
    {
     "rawSql": "SELECT distinct\n    setting_temperature as Badkamer\nFROM tado\nwhere $__timeFilter(\"time\") and zone_id = 7\n;"
    }
   ]
  },
  {
   "title": "Shelly",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT inside_temperature as \"temp\", humidity_percentage as \"vocht%\" \nFROM shelly \nWHERE $__timeFilter(\"time\") \nORDER BY \"time\" DESC LIMIT 1 "
    }
   ]
  },
  { "title": "Klimaat (trend)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Temperatuur",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT inside_temperature as woonkamer, heating_power_percentage, \"time\" FROM tado WHERE $__timeFilter(\"time\") AND zone_id = 1 ORDER BY \"time\" ASC "
    },
    {
     "rawSql": "SELECT inside_temperature as werkkamer, \"time\" FROM shelly WHERE $__timeFilter(\"time\") ORDER BY \"time\" ASC "
    },
    {
     "rawSql": "SELECT outside_temperature as buitenW, \"time\" FROM weather WHERE $__timeFilter(\"time\") ORDER BY \"time\" ASC "
    },
    {
     "rawSql": "SELECT outside_temperature as buiten, \"time\" FROM tado_outside WHERE $__timeFilter(\"time\") ORDER BY \"time\" ASC "
    }
   ]
  },
  {
   "title": "Sun",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT \"time\", solar_intensity_percentage FROM tado_outside WHERE $__timeFilter(\"time\") ORDER BY \"time\" ASC "
    },
    {
     "rawSql": "SELECT (uv/7.8)*(100-cloud) as calc_percentage, \"time\" FROM weather WHERE $__timeFilter(\"time\") ORDER BY \"time\" ASC"
    }
   ]
  },
  {
   "title": "Vocht%",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT humidity_percentage as werkkamer, \"time\" FROM shelly WHERE $__timeFilter(\"time\") ORDER BY \"time\" ASC "
    },
    {
     "rawSql": "SELECT humidity_percentage as woonkamer, \"time\" FROM tado WHERE $__timeFilter(\"time\") AND zone_id = 1 ORDER BY \"time\" ASC "
    },
    {
     "rawSql": "SELECT humidity_percentage as buiten, \"time\" FROM weather WHERE $__timeFilter(\"time\") ORDER BY \"time\" ASC "
    }
   ]
  },
  { "title": "Maand", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Electriciteit Totaal Per Maand (Kwh)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "rawSql": "select\n    min(time)::date as time,\n    max(power_normal_kwh) - min(power_normal_kwh) +\n    max(power_offpeak_kwh) - min(power_offpeak_kwh) as \"previous year\"\n    from electricity\n    where extract(year from time) = extract(year from now()) - 1\n    group by extract(year from time), extract(month from time)\n    order by 1;"
    },
    {
     "rawSql": "select\n    min(time)::date - INTERVAL '1 years' as time,\n    max(power_normal_kwh) - min(power_normal_kwh) +\n    max(power_offpeak_kwh) - min(power_offpeak_kwh) as \"current year\"\n    from electricity\n    where extract(year from time) = extract(year from now())\n    group by extract(year from time), extract(month from time)\n    order by 1;"
    }
   ]
  },
  {
   "title": "Vorig Jaar",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 44 },
   "targets": [
    {
     "data": "{\n  \"actualPreviousYear\": 1522.64,\n  \"actualYTD\": 47.362,\n  \"actualYTDPreviousYear\": 11.454,\n  \"actualRunningYear\": 1558.548,\n  \"yearExpectationExtrapolate\": 1728.7130000000002,\n  \"yearExpectationComparedWithLastYear\": 6296.07784878645\n}",
     "parser": "backend",
     "root_selector": "$.actualPreviousYear",
     "source": "url",
     "type": "json",
     "url": "http://192.168.2.39:8080/homewizard/electricity/summary",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "YTD Vorig Jaar",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 47 },
   "targets": [
    {
     "data": "{\n  \"actualPreviousYear\": 1522.64,\n  \"actualYTD\": 47.362,\n  \"actualYTDPreviousYear\": 11.454,\n  \"actualRunningYear\": 1558.548,\n  \"yearExpectationExtrapolate\": 1728.7130000000002,\n  \"yearExpectationComparedWithLastYear\": 6296.07784878645\n}",
     "parser": "backend",
     "root_selector": "$.actualYTDPreviousYear",
     "source": "url",
     "type": "json",
     "url": "http://192.168.2.39:8080/homewizard/electricity/summary",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "YTD",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 50 },
   "targets": [
    {
     "data": "{\n  \"actualPreviousYear\": 1522.64,\n  \"actualYTD\": 47.362,\n  \"actualYTDPreviousYear\": 11.454,\n  \"actualRunningYear\": 1558.548,\n  \"yearExpectationExtrapolate\": 1728.7130000000002,\n  \"yearExpectationComparedWithLastYear\": 6296.07784878645\n}",
     "parser": "backend",
     "root_selector": "$.actualYTD",
     "source": "url",
     "type": "json",
     "url": "http://192.168.2.39:8080/homewizard/electricity/summary",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "extrapolate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 53 },
   "targets": [
    {
     "data": "{\n  \"actualPreviousYear\": 1522.64,\n  \"actualYTD\": 47.362,\n  \"actualYTDPreviousYear\": 11.454,\n  \"actualRunningYear\": 1558.548,\n  \"yearExpectationExtrapolate\": 1728.7130000000002,\n  \"yearExpectationComparedWithLastYear\": 6296.07784878645\n}",
     "parser": "backend",
     "root_selector": "$.prognose.extrapolate",
     "source": "url",
     "type": "json",
     "url": "http://192.168.2.39:8080/homewizard/electricity/summary",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "trend 365d",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 53 },
   "targets": [
    {
     "data": "{\n  \"actualPreviousYear\": 1522.64,\n  \"actualYTD\": 47.362,\n  \"actualYTDPreviousYear\": 11.454,\n  \"actualRunningYear\": 1558.548,\n  \"yearExpectationExtrapolate\": 1728.7130000000002,\n  \"yearExpectationComparedWithLastYear\": 6296.07784878645\n}",
     "parser": "backend",
     "root_selector": "$.prognose.followTrendRollingYear",
     "source": "url",
     "type": "json",
     "url": "http://192.168.2.39:8080/homewizard/electricity/summary",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "trend 0d",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 53 },
   "targets": [
    {
     "data": "{\n  \"actualPreviousYear\": 1522.64,\n  \"actualYTD\": 47.362,\n  \"actualYTDPreviousYear\": 11.454,\n  \"actualRunningYear\": 1558.548,\n  \"yearExpectationExtrapolate\": 1728.7130000000002,\n  \"yearExpectationComparedWithLastYear\": 6296.07784878645\n}",
     "parser": "backend",
     "root_selector": "$.prognose.followPreviousYear",
     "source": "url",
     "type": "json",
     "url": "http://192.168.2.39:8080/homewizard/electricity/summary",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "trend 28d",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 53 },
   "targets": [
    {
     "data": "{\n  \"actualPreviousYear\": 1522.64,\n  \"actualYTD\": 47.362,\n  \"actualYTDPreviousYear\": 11.454,\n  \"actualRunningYear\": 1558.548,\n  \"yearExpectationExtrapolate\": 1728.7130000000002,\n  \"yearExpectationComparedWithLastYear\": 6296.07784878645\n}",
     "parser": "backend",
     "root_selector": "$.prognose.followTrend28Days",
     "source": "url",
     "type": "json",
     "url": "http://192.168.2.39:8080/homewizard/electricity/summary",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "trend weighted",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 53 },
   "targets": [
    {
     "data": "{\n  \"actualPreviousYear\": 1522.64,\n  \"actualYTD\": 47.362,\n  \"actualYTDPreviousYear\": 11.454,\n  \"actualRunningYear\": 1558.548,\n  \"yearExpectationExtrapolate\": 1728.7130000000002,\n  \"yearExpectationComparedWithLastYear\": 6296.07784878645\n}",
     "parser": "backend",
     "root_selector": "$.prognose.followTrendWeighted",
     "source": "url",
     "type": "json",
     "url": "http://192.168.2.39:8080/homewizard/electricity/summary",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "trend ytd",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 53 },
   "targets": [
    {
     "data": "{\n  \"actualPreviousYear\": 1522.64,\n  \"actualYTD\": 47.362,\n  \"actualYTDPreviousYear\": 11.454,\n  \"actualRunningYear\": 1558.548,\n  \"yearExpectationExtrapolate\": 1728.7130000000002,\n  \"yearExpectationComparedWithLastYear\": 6296.07784878645\n}",
     "parser": "backend",
     "root_selector": "$.prognose.followTrendYTD",
     "source": "url",
     "type": "json",
     "url": "http://192.168.2.39:8080/homewizard/electricity/summary",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Water Per Maand (M3)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "targets": [
    {
     "rawSql": "SELECT min(time)::date as time,\n       max(water_m3) - min(water_m3) as \"previous year\"\nFROM water\n    where extract(year from time) = extract(year from now()) - 1\ngroup by extract(year from time), extract(month from time)\norder by time;\n"
    },
    {
     "rawSql": "SELECT min(time)::date - INTERVAL '1 years' as time,\n       max(water_m3) - min(water_m3) as \"current year\"\nFROM water\n    where extract(year from time) = extract(year from now())\ngroup by extract(year from time), extract(month from time)\norder by time;\n"
    }
   ]
  },
  {
   "title": "Vorig jaar",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 56 },
   "targets": [
    {
     "data": "{\n  \"actualPreviousYear\": 1522.64,\n  \"actualYTD\": 47.362,\n  \"actualYTDPreviousYear\": 11.454,\n  \"actualRunningYear\": 1558.548,\n  \"yearExpectationExtrapolate\": 1728.7130000000002,\n  \"yearExpectationComparedWithLastYear\": 6296.07784878645\n}",
     "parser": "backend",
     "root_selector": "$.actualPreviousYear",
     "source": "url",
     "type": "json",
     "url": "http://192.168.2.39:8080/homewizard/water/summary",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "YTD Vorig jaar",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 59 },
   "targets": [
    {
     "data": "{\n  \"actualPreviousYear\": 1522.64,\n  \"actualYTD\": 47.362,\n  \"actualYTDPreviousYear\": 11.454,\n  \"actualRunningYear\": 1558.548,\n  \"yearExpectationExtrapolate\": 1728.7130000000002,\n  \"yearExpectationComparedWithLastYear\": 6296.07784878645\n}",
     "parser": "backend",
     "root_selector": "$.actualYTDPreviousYear",
     "source": "url",
     "type": "json",
     "url": "http://192.168.2.39:8080/homewizard/water/summary",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "YTD",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 62 },
   "targets": [
    {
     "data": "{\n  \"actualPreviousYear\": 1522.64,\n  \"actualYTD\": 47.362,\n  \"actualYTDPreviousYear\": 11.454,\n  \"actualRunningYear\": 1558.548,\n  \"yearExpectationExtrapolate\": 1728.7130000000002,\n  \"yearExpectationComparedWithLastYear\": 6296.07784878645\n}",
     "parser": "backend",
     "root_selector": "$.actualYTD",
     "source": "url",
     "type": "json",
     "url": "http://192.168.2.39:8080/homewizard/water/summary",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "extrapolate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 65 },
   "targets": [
    {
     "data": "{\n  \"actualPreviousYear\": 1522.64,\n  \"actualYTD\": 47.362,\n  \"actualYTDPreviousYear\": 11.454,\n  \"actualRunningYear\": 1558.548,\n  \"yearExpectationExtrapolate\": 1728.7130000000002,\n  \"yearExpectationComparedWithLastYear\": 6296.07784878645\n}",
     "parser": "backend",
     "root_selector": "$.prognose.extrapolate",
     "source": "url",
     "type": "json",
     "url": "http://192.168.2.39:8080/homewizard/water/summary",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "trend 365d",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 65 },
   "targets": [
    {
     "data": "{\n  \"actualPreviousYear\": 1522.64,\n  \"actualYTD\": 47.362,\n  \"actualYTDPreviousYear\": 11.454,\n  \"actualRunningYear\": 1558.548,\n  \"yearExpectationExtrapolate\": 1728.7130000000002,\n  \"yearExpectationComparedWithLastYear\": 6296.07784878645\n}",
     "parser": "backend",
     "root_selector": "$.prognose.followTrendRollingYear",
     "source": "url",
     "type": "json",
     "url": "http://192.168.2.39:8080/homewizard/water/summary",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "trend 0d",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 65 },
   "targets": [
    {
     "data": "{\n  \"actualPreviousYear\": 1522.64,\n  \"actualYTD\": 47.362,\n  \"actualYTDPreviousYear\": 11.454,\n  \"actualRunningYear\": 1558.548,\n  \"yearExpectationExtrapolate\": 1728.7130000000002,\n  \"yearExpectationComparedWithLastYear\": 6296.07784878645\n}",
     "parser": "backend",
     "root_selector": "$.prognose.followPreviousYear",
     "source": "url",
     "type": "json",
     "url": "http://192.168.2.39:8080/homewizard/water/summary",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "trend 28d",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 65 },
   "targets": [
    {
     "data": "{\n  \"actualPreviousYear\": 1522.64,\n  \"actualYTD\": 47.362,\n  \"actualYTDPreviousYear\": 11.454,\n  \"actualRunningYear\": 1558.548,\n  \"yearExpectationExtrapolate\": 1728.7130000000002,\n  \"yearExpectationComparedWithLastYear\": 6296.07784878645\n}",
     "parser": "backend",
     "root_selector": "$.prognose.followTrend28Days",
     "source": "url",
     "type": "json",
     "url": "http://192.168.2.39:8080/homewizard/water/summary",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "trend weighted",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 65 },
   "targets": [
    {
     "data": "{\n  \"actualPreviousYear\": 1522.64,\n  \"actualYTD\": 47.362,\n  \"actualYTDPreviousYear\": 11.454,\n  \"actualRunningYear\": 1558.548,\n  \"yearExpectationExtrapolate\": 1728.7130000000002,\n  \"yearExpectationComparedWithLastYear\": 6296.07784878645\n}",
     "parser": "backend",
     "root_selector": "$.prognose.followTrendWeighted",
     "source": "url",
     "type": "json",
     "url": "http://192.168.2.39:8080/homewizard/water/summary",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "trend ytd",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 65 },
   "targets": [
    {
     "data": "{\n  \"actualPreviousYear\": 1522.64,\n  \"actualYTD\": 47.362,\n  \"actualYTDPreviousYear\": 11.454,\n  \"actualRunningYear\": 1558.548,\n  \"yearExpectationExtrapolate\": 1728.7130000000002,\n  \"yearExpectationComparedWithLastYear\": 6296.07784878645\n}",
     "parser": "backend",
     "root_selector": "$.prognose.followTrendYTD",
     "source": "url",
     "type": "json",
     "url": "http://192.168.2.39:8080/homewizard/water/summary",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Energy Consumption Per Maand (GJ)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 68 },
   "targets": [
    {
     "rawSql": "SELECT min(time)::date as time,\n       max(heath_gj) - min(heath_gj) as \"previous year\"\nFROM heath\n    where extract(year from time) = extract(year from now())-1\ngroup by extract(year from time), extract(month from time)\norder by time;"
    },
    {
     "rawSql": "SELECT min(time)::date - INTERVAL '1 years' as time,\n       max(heath_gj) - min(heath_gj) as \"current year\"\nFROM heath\n    where extract(year from time) = extract(year from now())\ngroup by extract(year from time), extract(month from time)\norder by time;"
    }
   ]
  },
  {
   "title": "Vorig jaar",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 68 },
   "targets": [
    {
     "data": "{\n  \"actualPreviousYear\": 1522.64,\n  \"actualYTD\": 47.362,\n  \"actualYTDPreviousYear\": 11.454,\n  \"actualRunningYear\": 1558.548,\n  \"yearExpectationExtrapolate\": 1728.7130000000002,\n  \"yearExpectationComparedWithLastYear\": 6296.07784878645\n}",
     "parser": "backend",
     "root_selector": "$.actualPreviousYear",
     "source": "url",
     "type": "json",
     "url": "http://192.168.2.39:8080/eneco/summary",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "YTD Vorig jaar",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 71 },
   "targets": [
    {
     "data": "{\n  \"actualPreviousYear\": 1522.64,\n  \"actualYTD\": 47.362,\n  \"actualYTDPreviousYear\": 11.454,\n  \"actualRunningYear\": 1558.548,\n  \"yearExpectationExtrapolate\": 1728.7130000000002,\n  \"yearExpectationComparedWithLastYear\": 6296.07784878645\n}",
     "parser": "backend",
     "root_selector": "$.actualYTDPreviousYear",
     "source": "url",
     "type": "json",
     "url": "http://192.168.2.39:8080/eneco/summary",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "YTD",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 74 },
   "targets": [
    {
     "data": "{\n  \"actualPreviousYear\": 1522.64,\n  \"actualYTD\": 47.362,\n  \"actualYTDPreviousYear\": 11.454,\n  \"actualRunningYear\": 1558.548,\n  \"yearExpectationExtrapolate\": 1728.7130000000002,\n  \"yearExpectationComparedWithLastYear\": 6296.07784878645\n}",
     "parser": "backend",
     "root_selector": "$.actualYTD",
     "source": "url",
     "type": "json",
     "url": "http://192.168.2.39:8080/eneco/summary",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "extrapolate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 77 },
   "targets": [
    {
     "data": "{\n  \"actualPreviousYear\": 1522.64,\n  \"actualYTD\": 47.362,\n  \"actualYTDPreviousYear\": 11.454,\n  \"actualRunningYear\": 1558.548,\n  \"yearExpectationExtrapolate\": 1728.7130000000002,\n  \"yearExpectationComparedWithLastYear\": 6296.07784878645\n}",
     "parser": "backend",
     "root_selector": "$.prognose.extrapolate",
     "source": "url",
     "type": "json",
     "url": "http://192.168.2.39:8080/eneco/summary",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "trend 365d",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 77 },
   "targets": [
    {
     "data": "{\n  \"actualPreviousYear\": 1522.64,\n  \"actualYTD\": 47.362,\n  \"actualYTDPreviousYear\": 11.454,\n  \"actualRunningYear\": 1558.548,\n  \"yearExpectationExtrapolate\": 1728.7130000000002,\n  \"yearExpectationComparedWithLastYear\": 6296.07784878645\n}",
     "parser": "backend",
     "root_selector": "$.prognose.followTrendRollingYear",
     "source": "url",
     "type": "json",
     "url": "http://192.168.2.39:8080/eneco/summary",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "trend 0d",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 77 },
   "targets": [
    {
     "data": "{\n  \"actualPreviousYear\": 1522.64,\n  \"actualYTD\": 47.362,\n  \"actualYTDPreviousYear\": 11.454,\n  \"actualRunningYear\": 1558.548,\n  \"yearExpectationExtrapolate\": 1728.7130000000002,\n  \"yearExpectationComparedWithLastYear\": 6296.07784878645\n}",
     "parser": "backend",
     "root_selector": "$.prognose.followPreviousYear",
     "source": "url",
     "type": "json",
     "url": "http://192.168.2.39:8080/eneco/summary",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "trend 28d",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 77 },
   "targets": [
    {
     "data": "{\n  \"actualPreviousYear\": 1522.64,\n  \"actualYTD\": 47.362,\n  \"actualYTDPreviousYear\": 11.454,\n  \"actualRunningYear\": 1558.548,\n  \"yearExpectationExtrapolate\": 1728.7130000000002,\n  \"yearExpectationComparedWithLastYear\": 6296.07784878645\n}",
     "parser": "backend",
     "root_selector": "$.prognose.followTrend28Days",
     "source": "url",
     "type": "json",
     "url": "http://192.168.2.39:8080/eneco/summary",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "trend weighted",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 77 },
   "targets": [
    {
     "data": "{\n  \"actualPreviousYear\": 1522.64,\n  \"actualYTD\": 47.362,\n  \"actualYTDPreviousYear\": 11.454,\n  \"actualRunningYear\": 1558.548,\n  \"yearExpectationExtrapolate\": 1728.7130000000002,\n  \"yearExpectationComparedWithLastYear\": 6296.07784878645\n}",
     "parser": "backend",
     "root_selector": "$.prognose.followTrendWeighted",
     "source": "url",
     "type": "json",
     "url": "http://192.168.2.39:8080/eneco/summary",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "trend ytd",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 77 },
   "targets": [
    {
     "data": "{\n  \"actualPreviousYear\": 1522.64,\n  \"actualYTD\": 47.362,\n  \"actualYTDPreviousYear\": 11.454,\n  \"actualRunningYear\": 1558.548,\n  \"yearExpectationExtrapolate\": 1728.7130000000002,\n  \"yearExpectationComparedWithLastYear\": 6296.07784878645\n}",
     "parser": "backend",
     "root_selector": "$.prognose.followTrendYTD",
     "source": "url",
     "type": "json",
     "url": "http://192.168.2.39:8080/eneco/summary",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Maand (extra warmte info)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 },
   "collapsed": true,
   "panels": [
    {
     "title": "call for heat per maand (totaal)",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 20, "x": 0, "y": 321 },
     "targets": [
      {
       "rawSql": "SELECT min(time)::date as time,\n       sum(call_for_heat) as \"2024\"\nFROM tado_hour_aggregate \n    where extract(year from time) = extract(year from now())-1 \ngroup by extract(year from time), extract(month from time)\norder by time;"
      },
      {
       "rawSql": "SELECT min(time)::date - INTERVAL '1 years' as time,\n       sum(call_for_heat) as \"2025\"\nFROM tado_hour_aggregate \n    where extract(year from time) = extract(year from now())\ngroup by extract(year from time), extract(month from time)\norder by time;"
      }
     ]
    },
    {
     "title": "Buitentemperatuur per maand (gemiddeld)",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 20, "x": 0, "y": 329 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "rawSql": "SELECT min(time)::date as time,\n       avg(outside_temperature) as \"2024\"\nFROM tado_hour_aggregate \n    where extract(year from time) = extract(year from now())-1\ngroup by extract(year from time), extract(month from time)\norder by time;"
      },
      {
       "rawSql": "SELECT min(time)::date - INTERVAL '1 years' as time,\n       avg(outside_temperature) as \"2025\"\nFROM tado_hour_aggregate \n    where extract(year from time) = extract(year from now())\ngroup by extract(year from time), extract(month from time)\norder by time;"
      }
     ]
    },
    {
     "title": "Zonminuten per maand (totaal)",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 20, "x": 0, "y": 436 },
     "targets": [
      {
       "rawSql": "SELECT min(time)::date as time,\n       sum(sunny_minutes) as \"2024\"\nFROM tado_hour_aggregate \n    where extract(year from time) = extract(year from now())-1\ngroup by extract(year from time), extract(month from time)\norder by time;"
      },
      {
       "rawSql": "SELECT min(time)::date - INTERVAL '1 years' as time,\n       sum(sunny_minutes) as \"2025\"\nFROM tado_hour_aggregate \n    where extract(year from time) = extract(year from now())\ngroup by extract(year from time), extract(month from time)\norder by time;"
      }
     ]
    },
    {
     "title": "Binnentemperatuur per maand (gemiddeld)",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 20, "x": 0, "y": 444 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "rawSql": "SELECT min(time)::date as time,\n       avg(inside_temperature) as \"2024\"\nFROM tado_hour_aggregate \n    where extract(year from time) = extract(year from now())-1\ngroup by extract(year from time), extract(month from time)\norder by time;"
      },
      {
       "rawSql": "SELECT min(time)::date - INTERVAL '1 years' as time,\n       avg(inside_temperature) as \"2025\"\nFROM tado_hour_aggregate \n    where extract(year from time) = extract(year from now())\ngroup by extract(year from time), extract(month from time)\norder by time;"
      }
     ]
    }
   ]
  },
  {
   "title": "Nu",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 },
   "repeat": "NowPeriod",
   "collapsed": true,
   "panels": [
    {
     "title": "Water (Lpm)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 666 },
     "targets": [
      { "expr": "homewizardWaterActiveLpm", "legendFormat": "water" }
     ]
    },
    {
     "title": "Power",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 666 },
     "targets": [
      {
       "expr": "homewizardActivePowerL1Watt + homewizardActivePowerL2Watt + homewizardActivePowerL3Watt",
       "legendFormat": "power"
      }
     ]
    }
   ]
  },
  {
   "title": "Uur",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 },
   "collapsed": true,
   "panels": [
    {
     "title": "Electriciteit Totaal Per Uur (Kwh)",
     "type": "barchart",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 667 },
     "fieldConfig": { "defaults": { "unit": "kwatth" } },
     "targets": [
      {
       "rawSql": "SELECT min(time) as time,\n       max(power_normal_kwh) - min(power_normal_kwh) as power_normal_kwh,\n       max(power_offpeak_kwh) - min(power_offpeak_kwh) as power_offpeak_kwh\nFROM electricity\n    where $__timeFilter(time)\ngroup by extract(year from time), extract(month from time),extract(day from time),extract(hour from time)\norder by time;"
      }
     ]
    },
    {
     "title": "Water Per Uur (Ltr)",
     "type": "barchart",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 857 },
     "fieldConfig": { "defaults": { "unit": "litre" } },
     "targets": [
      {
       "rawSql": "SELECT min(time) as time,\n       1000*(max(water_m3) - min(water_m3)) as water_m3\nFROM water\n    where $__timeFilter(time)\ngroup by extract(year from time), extract(month from time),extract(day from time),extract(hour from time)\norder by time;\n"
      }
     ]
    },
    {
     "title": "Energy Consumption Per Hour (GJ)",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 864 },
     "targets": [
      {
       "rawSql": "SELECT min(time) as time,\n       sum(delta_gj) as delta_heath_gj\nFROM heath\n    where $__timeFilter(time)\ngroup by extract(year from time), extract(month from time),extract(day from time),extract(hour from time)\norder by time;"
      }
     ]
    }
   ]
  },
  {
   "title": "Dag",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 },
   "collapsed": true,
   "panels": [
    {
     "title": "Electriciteit Totaal Per Dag (Kwh)",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 668 },
     "fieldConfig": { "defaults": { "unit": "kwatth" } },
     "targets": [
      {
       "rawSql": "SELECT min(time) as time,\n       max(power_normal_kwh) - min(power_normal_kwh) as normal_kwh,\n       max(power_offpeak_kwh) - min(power_offpeak_kwh) as offpeak_kwh\nFROM electricity\n    where $__timeFilter(time)\ngroup by extract(year from time), extract(month from time),extract(day from time)\norder by time;"
      }
     ]
    },
    {
     "title": "Water Per Dag (Ltr)",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 685 },
     "fieldConfig": { "defaults": { "unit": "litre" } },
     "targets": [
      {
       "rawSql": "SELECT min(time) as time,\n       1000*(max(water_m3) - min(water_m3)) as water_m3\nFROM water\n    where $__timeFilter(time)\ngroup by extract(year from time), extract(month from time),extract(day from time)\norder by time;\n"
      }
     ]
    },
    {
     "title": "Energy Consumption Per Day (GJ)",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 693 },
     "targets": [
      {
       "rawSql": "SELECT min(time) as time,\n       max(heath_gj) - min(heath_gj) as heath_gj\nFROM heath\n    where $__timeFilter(time)\ngroup by extract(year from time), extract(month from time),extract(day from time)\norder by time;"
      }
     ]
    }
   ]
  },
  {
   "title": "Meterkast",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 },
   "collapsed": true,
   "panels": [
    {
     "title": "Hoog DB (kwh)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1318 },
     "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT \"time\", power_normal_kwh FROM electricity ORDER BY \"time\" DESC LIMIT 1 "
      }
     ]
    },
    {
     "title": "Laag DB (kwh)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1318 },
     "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT \"time\", power_offpeak_kwh FROM electricity ORDER BY \"time\" DESC LIMIT 1 "
      }
     ]
    },
    {
     "title": "WaterStand DB (M3)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1318 },
     "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT \"time\", water_m3 FROM water ORDER BY \"time\" DESC LIMIT 1 "
      }
     ]
    },
    {
     "title": "Energy Consumption Stand DB (GJ)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1318 },
     "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT \"time\", heath_gj FROM heath ORDER BY \"time\" DESC LIMIT 1 "
      }
     ]
    },
    {
     "title": "Electriciteit stand (Laag) Per Maand (Kwh)",
     "type": "barchart",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1322 },
     "targets": [
      {
       "rawSql": "select\n    min(time)::date as time,\n    min(power_offpeak_kwh) as laag\n    from electricity\n    where $__timeFilter(time)\n    group by extract(year from time), extract(month from time)\n    order by 1;"
      }
     ]
    },
    {
     "title": "Electriciteit stand (Hoog) Per Maand (Kwh)",
     "type": "barchart",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1322 },
     "targets": [
      {
       "rawSql": "select\n    min(time)::date as time,\n    min(power_normal_kwh) as hoog\n    from electricity\n    where $__timeFilter(time)\n    group by extract(year from time), extract(month from time)\n    order by 1;"
      }
     ]
    },
    {
     "title": "Water stand Per Maand (M3)",
     "type": "barchart",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1329 },
     "fieldConfig": { "defaults": { "unit": "m3" } },
     "targets": [
      {
       "rawSql": "select\n    min(time)::date as time,\n    min(water_m3) as water\n    from water\n    where $__timeFilter(time)\n    group by extract(year from time), extract(month from time)\n    order by 1;"
      }
     ]
    },
    {
     "title": "Energy stand Per Maand (GJ)",
     "type": "barchart",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1329 },
     "targets": [
      {
       "rawSql": "select\n    min(time)::date as time,\n    min(heath_GJ) as warmte\n    from heath\n    where $__timeFilter(time)\n    group by extract(year from time), extract(month from time)\n    order by 1;"
      }
     ]
    },
    {
     "title": "Manual correction (GJ)",
     "type": "barchart",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1336 },
     "targets": [
      {
       "rawSql": "select\n    time,\n    heath_GJ\n    from manual_heath_correction\n    where $__timeFilter(time)\n    order by 1;"
      }
     ]
    }
   ]
  },
  {
   "title": "Log",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 },
   "collapsed": true,
   "panels": [
    {
     "title": "Taco Counters",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 104 },
     "options": { "reduceOptions": { "calcs": [ "range" ] } },
     "targets": [
      { "expr": "tado_get_total", "legendFormat": "get" },
      { "expr": "tado_post_total", "legendFormat": "post" }
     ]
    },
    {
     "title": "Logs",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 108 },
     "targets": [
      {
       "parser": "backend",
       "source": "url",
       "type": "json",
       "url": "http://192.168.2.39:8080/log/logs",
       "url_options": { "data": "", "method": "GET" }
      }
     ]
    }
   ]
  },
  {
   "title": "Overig",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 },
   "collapsed": true,
   "panels": [
    {
     "title": "Showers (ltrs)",
     "type": "barchart",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 105 },
     "fieldConfig": { "defaults": { "unit": "litre" } },
     "targets": [
      {
       "rawSql": "select\n    time,\n    liters\n    from shower_usage \n    where $__timeFilter(time)\n    order by time;"
      }
     ]
    },
    {
     "title": "Showers (gj)",
     "type": "barchart",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 112 },
     "targets": [
      {
       "rawSql": "select\n    time,\n    heat_gj\n    from shower_usage \n    where $__timeFilter(time)\n    order by time;"
      }
     ]
    },
    {
     "title": "Electriciteit Totaal Per Maand DB (Kwh)",
     "type": "barchart",
     "gridPos": { "h": 9, "w": 14, "x": 0, "y": 119 },
     "fieldConfig": { "defaults": { "unit": "kwatth" } },
     "targets": [
      {
       "rawSql": "select\n    min(time)::date as firstDate,\n    max(power_normal_kwh) - min(power_normal_kwh) as normal_kwh,\n    max(power_offpeak_kwh) - min(power_offpeak_kwh) as offpeak_kwh\n    from electricity\n    where $__timeFilter(time)\n    group by extract(year from time), extract(month from time)\n    order by 1;"
      }
     ]
    },
    {
     "title": "Tado Battery",
     "type": "table",
     "gridPos": { "h": 7, "w": 10, "x": 14, "y": 119 },
     "targets": [
      {
       "rawSql": "SELECT zone_name, serial_number, battery_state FROM tado_device_state "
      }
     ]
    },
    {
     "title": "Total €",
     "type": "stat",
     "gridPos": { "h": 2, "w": 10, "x": 14, "y": 126 },
     "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "  select\n    (\n      max(power_normal_kwh) - min(power_normal_kwh) + max(power_offpeak_kwh) - min(power_offpeak_kwh)\n    ) *.21\n  from\n    electricity\n  where\n    $__timeFilter(\"time\")\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Smart Plug (turned off)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 },
   "collapsed": true,
   "panels": [
    {
     "title": "Smart Plug Per Day (Percentage)",
     "type": "barchart",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 106 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "rawSql": "with totals as\n    (select min(time)::date as day,\n           (max(power_normal_kwh) - min(power_normal_kwh) +\n            max(power_offpeak_kwh) - min(power_offpeak_kwh)) * 1000 as totaldaypower\n    from electricity\n    where $__timeFilter(\"time\") \n    group by extract(year from time), extract(month from time), extract(day from time)\n    )\n  , smart as\n     (select min(time)::date as day,\n             name,\n             sum(delta_wh) as power\n      from electricity_hour_detail\n      where $__timeFilter(\"time\") and (name != 'Marantz Versterker')\n      group by name, extract(year from time), extract(month from time), extract(day from time)\n)\n\nselect smart.day, name, power/totaldaypower as \"%\"\nfrom totals inner join smart on totals.day = smart.day\norder by 1\n;\n"
      }
     ]
    },
    {
     "title": "Smart Plug Per Week (Wh)",
     "type": "barchart",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 116 },
     "fieldConfig": { "defaults": { "unit": "watth" } },
     "targets": [
      {
       "rawSql": "select \n  to_date(concat(extract(year from time),extract(week from time)), 'iyyyiw') as week, \n  name, \n  sum(delta_wh) as \" \"\nfrom electricity_hour_detail\nwhere $__timeFilter(time) \nGROUP BY week, name\nORDER BY week, name;"
      }
     ]
    },
    {
     "title": "Smart Plug Per Hour (Wh)",
     "type": "barchart",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 123 },
     "fieldConfig": { "defaults": { "unit": "watth" } },
     "targets": [
      {
       "rawSql": "SELECT\n  time,\n  case when isvirtual then name || '*' else name end,\n  delta_wh as \" \"\nFROM electricity_hour_detail\nWHERE\n  $__timeFilter(\"time\")\nORDER BY time, name;"
      }
     ]
    },
    {
     "title": "Smart Plug Status",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 130 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "rawSql": "select time, (number_known-number_on_line) as offline, number_on_line as online from smart_plug_status where $__timeFilter(time) order by time"
      }
     ]
    },
    {
     "title": "Smart Plug Per Day (WH)",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 134 },
     "fieldConfig": { "defaults": { "unit": "watth" } },
     "targets": [
      {
       "rawSql": "select \n  date_trunc('day', time) as day, \n  case when isvirtual then name || '*' else name end as name, \n  sum(delta_wh) as \" \"\nfrom electricity_hour_detail\nwhere $__timeFilter(time) \nGROUP BY day, name, isvirtual\nORDER BY day, name;"
      }
     ]
    },
    {
     "title": "Smart Plug Per Maand (Wh)",
     "type": "barchart",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 142 },
     "fieldConfig": { "defaults": { "unit": "watth" } },
     "targets": [
      {
       "rawSql": "select \n  date_trunc('month', time) as month,\n  name, \n  sum(delta_wh) as \" \"\nfrom electricity_hour_detail\nwhere $__timeFilter(\"time\") \ngroup by month, name\nORDER by month, name"
      }
     ]
    },
    {
     "title": "Smart Plug  (Total Wattage)",
     "type": "barchart",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 149 },
     "fieldConfig": { "defaults": { "unit": "watth" } },
     "targets": [
      {
       "rawSql": "with totals as\n    (select\n           (max(power_normal_kwh) - min(power_normal_kwh) +\n            max(power_offpeak_kwh) - min(power_offpeak_kwh)) * 1000 as totaldaypower\n    from electricity\n    where $__timeFilter(\"time\") \n    )\n  , smart as\n     (select min(time)::date as day,\n             name,\n             sum(coalesce(delta_wh,0)) as power\n      from electricity_hour_detail\n      where $__timeFilter(\"time\") and (name != 'Marantz Versterker')\n      group by name, extract(century from time)\n)\n\nselect name, power \nfrom smart\norder by power\n;\n"
      }
     ]
    },
    {
     "title": "Smart Plug  (€)",
     "type": "barchart",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 159 },
     "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
     "targets": [
      {
       "rawSql": "with totals as (\n  select\n    (\n      max(power_normal_kwh) - min(power_normal_kwh) + max(power_offpeak_kwh) - min(power_offpeak_kwh)\n    ) * 1000 as totaldaypower\n  from\n    electricity\n  where\n    $__timeFilter(\"time\")\n),\nsmart as (\n  select\n    min(time) :: date as day,\n    name,\n    sum(coalesce(delta_wh, 0)) as power\n  from\n    electricity_hour_detail\n  where\n    $__timeFilter(\"time\")\n    and (name != 'Marantz Versterker')\n  group by\n    name,\n    extract(\n      century\n      from\n        time\n    )\n)\nselect\n  name,\n  (power/1000 ) * .21 as euro\nfrom\n  smart\norder by\n  power;"
      }
     ]
    },
    {
     "title": "Smart Plug  (Total Percentage)",
     "type": "barchart",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 170 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "rawSql": "with totals as\n    (select\n           (max(power_normal_kwh) - min(power_normal_kwh) +\n            max(power_offpeak_kwh) - min(power_offpeak_kwh)) * 1000 as totaldaypower\n    from electricity\n    where $__timeFilter(\"time\") \n    )\n  , smart as\n     (select min(time)::date as day,\n             name,\n             sum(coalesce(delta_wh,0)) as power\n      from electricity_hour_detail\n      where $__timeFilter(\"time\") and (name != 'Marantz Versterker')\n      group by name, extract(century from time)\n)\n\nselect name, power/(select totaldaypower from totals) as \"%\"\nfrom smart\norder by \"%\"\n;\n"
      }
     ]
    }
   ]
  }
 ]
}